export const stores = [
  {
    ID: "ST035",
    Label: "San Francisco Bay Trends",
    City: "San Francisco",
    State: "CA",
  },
  {
    ID: "ST046",
    Label: "Phoenix Sunwear",
    City: "Phoenix",
    State: "AZ",
  },
  {
    ID: "ST064",
    Label: "Dallas Ranch Supply",
    City: "Dallas",
    State: "TX",
  },
  {
    ID: "ST066",
    Label: "Atlanta Outfitters",
    City: "Atlanta",
    State: "GA",
  },
  {
    ID: "ST073",
    Label: "Nashville Melody Music Store",
    City: "Nashville",
    State: "TN",
  },
  {
    ID: "ST074",
    Label: "New York Empire Eats",
    City: "New York",
    State: "NY",
  },
  {
    ID: "ST091",
    Label: "Denver Peaks Outdoor",
    City: "Denver",
    State: "CO",
  },
  {
    ID: "ST094",
    Label: "Philadelphia Liberty Market",
    City: "Philadelphia",
    State: "PA",
  },
  {
    ID: "ST097",
    Label: "Boston Harbor Books",
    City: "Boston",
    State: "MA",
  },
  {
    ID: "ST101",
    Label: "Austin Vibe Co.",
    City: "Austin",
    State: "TX",
  },
  {
    ID: "ST131",
    Label: "Los Angeles Luxe",
    City: "Los Angeles",
    State: "CA",
  },
  {
    ID: "ST150",
    Label: "Houston Harvest Market",
    City: "Houston",
    State: "TX",
  },
  {
    ID: "ST151",
    Label: "Portland Evergreen Goods",
    City: "Portland",
    State: "OR",
  },
  {
    ID: "ST156",
    Label: "Chicago Charm Boutique",
    City: "Chicago",
    State: "IL",
  },
  {
    ID: "ST163",
    Label: "Las Vegas Neon Treasures",
    City: "Las Vegas",
    State: "NV",
  },
  {
    ID: "ST175",
    Label: "Seattle Skyline Goods",
    City: "Seattle",
    State: "WA",
  },
  {
    ID: "ST176",
    Label: "Miami Breeze Apparel",
    City: "Miami",
    State: "FL",
  },
  {
    ID: "ST177",
    Label: "San Diego Wave Surf Shop",
    City: "San Diego",
    State: "CA",
  },
  {
    ID: "ST193",
    Label: "Charlotte Queen‚Äôs Closet",
    City: "Charlotte",
    State: "NC",
  },
  {
    ID: "ST208",
    Label: "Detroit Motor Gear",
    City: "Detroit",
    State: "MI",
  },
];

export const sku = [
  {
    ID: "SK00158",
    Label: "Crew Neck Merino Wool Sweater",
    Class: "Tops",
    Department: "Men's Apparel",
    Price: " $114.99 ",
    Cost: " $18.28 ",
  },
  {
    ID: "SK00269",
    Label: "Faux Leather Leggings",
    Class: "Jewelry",
    Department: "Footwear",
    Price: " $9.99 ",
    Cost: " $8.45 ",
  },
  {
    ID: "SK00300",
    Label: "Fleece-Lined Parka",
    Class: "Jewelry",
    Department: "Unisex Accessories",
    Price: " $199.99 ",
    Cost: " $17.80 ",
  },
  {
    ID: "SK00304",
    Label: "Cotton Polo Shirt",
    Class: "Tops",
    Department: "Women's Apparel",
    Price: " $139.99 ",
    Cost: " $10.78 ",
  },
  {
    ID: "SK00766",
    Label: "Foldable Travel Hat",
    Class: "Tops",
    Department: "Footwear",
    Price: " $44.99 ",
    Cost: " $27.08 ",
  },
  {
    ID: "SK00786",
    Label: "Chic Quilted Wallet",
    Class: "Bottoms",
    Department: "Footwear",
    Price: " $14.99 ",
    Cost: " $4.02 ",
  },
  {
    ID: "SK00960",
    Label: "High-Slit Maxi Dress",
    Class: "Outerwear",
    Department: "Sportswear",
    Price: " $74.99 ",
    Cost: " $47.47 ",
  },
  {
    ID: "SK01183",
    Label: "Turtleneck Cable Knit Sweater",
    Class: "Footwear",
    Department: "Footwear",
    Price: " $49.99 ",
    Cost: " $22.60 ",
  },
  {
    ID: "SK01189",
    Label: "Retro-Inspired Sunglasses",
    Class: "Bottoms",
    Department: "Women's Apparel",
    Price: " $194.99 ",
    Cost: " $115.63 ",
  },
  {
    ID: "SK01193",
    Label: "Stretch Denim Overalls",
    Class: "Bottoms",
    Department: "Unisex Accessories",
    Price: " $129.99 ",
    Cost: " $47.06 ",
  },
  {
    ID: "SK01249",
    Label: "Adjustable Elastic Headband",
    Class: "Footwear",
    Department: "Women's Apparel",
    Price: " $19.99 ",
    Cost: " $1.34 ",
  },
  {
    ID: "SK01319",
    Label: "Adjustable Baseball Cap",
    Class: "Jewelry",
    Department: "Men's Apparel",
    Price: " $4.99 ",
    Cost: " $2.29 ",
  },
  {
    ID: "SK01349",
    Label: "Cotton Polo Shirt",
    Class: "Bottoms",
    Department: "Unisex Accessories",
    Price: " $114.99 ",
    Cost: " $60.94 ",
  },
  {
    ID: "SK01549",
    Label: "Faux Suede Ankle Boots",
    Class: "Tops",
    Department: "Sportswear",
    Price: " $94.99 ",
    Cost: " $71.53 ",
  },
  {
    ID: "SK01566",
    Label: "Striped Cotton Socks",
    Class: "Accessories",
    Department: "Sportswear",
    Price: " $9.99 ",
    Cost: " $6.91 ",
  },
  {
    ID: "SK01642",
    Label: "Performance Compression Tights",
    Class: "Outerwear",
    Department: "Sportswear",
    Price: " $54.99 ",
    Cost: " $59.61 ",
  },
  {
    ID: "SK01733",
    Label: "Vintage Logo Hoodie",
    Class: "Accessories",
    Department: "Men's Apparel",
    Price: " $94.99 ",
    Cost: " $84.45 ",
  },
  {
    ID: "SK01896",
    Label: "Floral Chiffon Wrap Dress",
    Class: "Accessories",
    Department: "Unisex Accessories",
    Price: " $149.99 ",
    Cost: " $68.55 ",
  },
  {
    ID: "SK01927",
    Label: "Asymmetrical Hem Skirt",
    Class: "Jewelry",
    Department: "Sportswear",
    Price: " $99.99 ",
    Cost: " $66.89 ",
  },
  {
    ID: "SK01950",
    Label: "Slim Fit Pinstripe Suit",
    Class: "Bottoms",
    Department: "Women's Apparel",
    Price: " $99.99 ",
    Cost: " $13.30 ",
  },
  {
    ID: "SK02029",
    Label: "Chunky Heel Sandals",
    Class: "Jewelry",
    Department: "Unisex Accessories",
    Price: " $89.99 ",
    Cost: " $46.70 ",
  },
  {
    ID: "SK02429",
    Label: "Suede Fringe Vest",
    Class: "Bottoms",
    Department: "Footwear",
    Price: " $184.99 ",
    Cost: " $159.65 ",
  },
  {
    ID: "SK02448",
    Label: "Relaxed Fit Cargo Pants",
    Class: "Bottoms",
    Department: "Sportswear",
    Price: " $149.99 ",
    Cost: " $7.20 ",
  },
  {
    ID: "SK02562",
    Label: "Corduroy A-Line Skirt",
    Class: "Jewelry",
    Department: "Footwear",
    Price: " $129.99 ",
    Cost: " $48.62 ",
  },
  {
    ID: "SK02642",
    Label: "Formal Dress Shoes",
    Class: "Bottoms",
    Department: "Women's Apparel",
    Price: " $164.99 ",
    Cost: " $161.69 ",
  },
  {
    ID: "SK02768",
    Label: "Tailored Corduroy Blazer",
    Class: "Accessories",
    Department: "Sportswear",
    Price: " $89.99 ",
    Cost: " $62.99 ",
  },
  {
    ID: "SK02805",
    Label: "Foldable Travel Hat",
    Class: "Outerwear",
    Department: "Women's Apparel",
    Price: " $194.99 ",
    Cost: " $56.16 ",
  },
  {
    ID: "SK02904",
    Label: "Asymmetrical Hem Skirt",
    Class: "Tops",
    Department: "Unisex Accessories",
    Price: " $89.99 ",
    Cost: " $67.94 ",
  },
  {
    ID: "SK03182",
    Label: "Plaid Flannel Shirt",
    Class: "Tops",
    Department: "Unisex Accessories",
    Price: " $124.99 ",
    Cost: " $17.50 ",
  },
  {
    ID: "SK03289",
    Label: "Oversized Hoodie",
    Class: "Tops",
    Department: "Women's Apparel",
    Price: " $159.99 ",
    Cost: " $122.23 ",
  },
  {
    ID: "SK03348",
    Label: "Woven Straw Sun Hat",
    Class: "Jewelry",
    Department: "Footwear",
    Price: " $164.99 ",
    Cost: " $8.91 ",
  },
  {
    ID: "SK03569",
    Label: "Faux Fur Winter Coat",
    Class: "Tops",
    Department: "Men's Apparel",
    Price: " $9.99 ",
    Cost: " $7.37 ",
  },
  {
    ID: "SK03572",
    Label: "Casual Cotton Romper",
    Class: "Tops",
    Department: "Footwear",
    Price: " $119.99 ",
    Cost: " $52.32 ",
  },
  {
    ID: "SK03636",
    Label: "Racerback Sports Bra",
    Class: "Footwear",
    Department: "Unisex Accessories",
    Price: " $14.99 ",
    Cost: " $8.72 ",
  },
  {
    ID: "SK03725",
    Label: "Polarized Sports Sunglasses",
    Class: "Tops",
    Department: "Men's Apparel",
    Price: " $79.99 ",
    Cost: " $9.44 ",
  },
  {
    ID: "SK03980",
    Label: "Chunky Platform Sneakers",
    Class: "Tops",
    Department: "Unisex Accessories",
    Price: " $109.99 ",
    Cost: " $61.70 ",
  },
  {
    ID: "SK04282",
    Label: "Slim Fit Chinos",
    Class: "Footwear",
    Department: "Sportswear",
    Price: " $114.99 ",
    Cost: " $51.98 ",
  },
  {
    ID: "SK04325",
    Label: "Faux Leather Leggings",
    Class: "Tops",
    Department: "Footwear",
    Price: " $194.99 ",
    Cost: " $13.06 ",
  },
  {
    ID: "SK04707",
    Label: "Water-Resistant Fanny Pack",
    Class: "Tops",
    Department: "Women's Apparel",
    Price: " $24.99 ",
    Cost: " $23.64 ",
  },
  {
    ID: "SK04815",
    Label: "Performance Compression Tights",
    Class: "Bottoms",
    Department: "Footwear",
    Price: " $14.99 ",
    Cost: " $16.29 ",
  },
  {
    ID: "SK05097",
    Label: "Cropped Faux Leather Jacket",
    Class: "Jewelry",
    Department: "Sportswear",
    Price: " $79.99 ",
    Cost: " $19.52 ",
  },
  {
    ID: "SK05194",
    Label: "Breathable Mesh Shorts",
    Class: "Accessories",
    Department: "Footwear",
    Price: " $194.99 ",
    Cost: " $28.08 ",
  },
  {
    ID: "SK05478",
    Label: "Minimalist Silver Ring",
    Class: "Accessories",
    Department: "Footwear",
    Price: " $174.99 ",
    Cost: " $147.34 ",
  },
  {
    ID: "SK05715",
    Label: "Ribbed Turtleneck Dress",
    Class: "Bottoms",
    Department: "Footwear",
    Price: " $94.99 ",
    Cost: " $22.61 ",
  },
  {
    ID: "SK05928",
    Label: "Velvet Slip Dress",
    Class: "Jewelry",
    Department: "Men's Apparel",
    Price: " $69.99 ",
    Cost: " $41.64 ",
  },
  {
    ID: "SK06290",
    Label: "Waterproof Smartwatch",
    Class: "Bottoms",
    Department: "Men's Apparel",
    Price: " $144.99 ",
    Cost: " $53.50 ",
  },
  {
    ID: "SK06375",
    Label: "Patterned Cotton Bucket Hat",
    Class: "Outerwear",
    Department: "Sportswear",
    Price: " $144.99 ",
    Cost: " $114.40 ",
  },
  {
    ID: "SK06559",
    Label: "Diamond Stud Earrings",
    Class: "Outerwear",
    Department: "Men's Apparel",
    Price: " $144.99 ",
    Cost: " $146.00 ",
  },
  {
    ID: "SK06601",
    Label: "Tassel Fringe Handbag",
    Class: "Outerwear",
    Department: "Unisex Accessories",
    Price: " $59.99 ",
    Cost: " $33.29 ",
  },
  {
    ID: "SK06651",
    Label: "Tactical Hiking Backpack",
    Class: "Outerwear",
    Department: "Sportswear",
    Price: " $49.99 ",
    Cost: " $52.54 ",
  },
  {
    ID: "SK06691",
    Label: "Patterned Cotton Bucket Hat",
    Class: "Accessories",
    Department: "Unisex Accessories",
    Price: " $9.99 ",
    Cost: " $2.14 ",
  },
  {
    ID: "SK06996",
    Label: "Bohemian Beaded Bracelet",
    Class: "Accessories",
    Department: "Unisex Accessories",
    Price: " $124.99 ",
    Cost: " $116.12 ",
  },
  {
    ID: "SK07054",
    Label: "Mesh Panel Yoga Pants",
    Class: "Accessories",
    Department: "Footwear",
    Price: " $184.99 ",
    Cost: " $166.86 ",
  },
  {
    ID: "SK07068",
    Label: "Diamond Stud Earrings",
    Class: "Outerwear",
    Department: "Sportswear",
    Price: " $14.99 ",
    Cost: " $13.75 ",
  },
  {
    ID: "SK07322",
    Label: "Faux Suede Ankle Boots",
    Class: "Tops",
    Department: "Footwear",
    Price: " $84.99 ",
    Cost: " $90.43 ",
  },
  {
    ID: "SK07369",
    Label: "Water-Resistant Fanny Pack",
    Class: "Outerwear",
    Department: "Unisex Accessories",
    Price: " $4.99 ",
    Cost: " $3.73 ",
  },
  {
    ID: "SK07447",
    Label: "Plaid Wool Scarf",
    Class: "Tops",
    Department: "Footwear",
    Price: " $139.99 ",
    Cost: " $97.57 ",
  },
  {
    ID: "SK07484",
    Label: "Cropped Faux Leather Jacket",
    Class: "Accessories",
    Department: "Women's Apparel",
    Price: " $179.99 ",
    Cost: " $163.43 ",
  },
  {
    ID: "SK07595",
    Label: "Textured Knit Pullover",
    Class: "Tops",
    Department: "Footwear",
    Price: " $54.99 ",
    Cost: " $50.43 ",
  },
  {
    ID: "SK07767",
    Label: "Boho Style Tassel Earrings",
    Class: "Footwear",
    Department: "Sportswear",
    Price: " $194.99 ",
    Cost: " $193.43 ",
  },
  {
    ID: "SK07782",
    Label: "Sherpa Lined Hooded Coat",
    Class: "Jewelry",
    Department: "Footwear",
    Price: " $174.99 ",
    Cost: " $128.09 ",
  },
  {
    ID: "SK07944",
    Label: "Mesh Panel Yoga Pants",
    Class: "Tops",
    Department: "Unisex Accessories",
    Price: " $69.99 ",
    Cost: " $45.49 ",
  },
  {
    ID: "SK08191",
    Label: "Graphic Print T-Shirt",
    Class: "Jewelry",
    Department: "Men's Apparel",
    Price: " $109.99 ",
    Cost: " $53.35 ",
  },
  {
    ID: "SK08285",
    Label: "Fitted V-Neck Sweater",
    Class: "Footwear",
    Department: "Men's Apparel",
    Price: " $124.99 ",
    Cost: " $110.24 ",
  },
  {
    ID: "SK08314",
    Label: "Formal Dress Shoes",
    Class: "Accessories",
    Department: "Footwear",
    Price: " $74.99 ",
    Cost: " $8.62 ",
  },
  {
    ID: "SK08373",
    Label: "Satin Lace Camisole",
    Class: "Jewelry",
    Department: "Women's Apparel",
    Price: " $184.99 ",
    Cost: " $136.15 ",
  },
  {
    ID: "SK08443",
    Label: "Slim Fit Chinos",
    Class: "Bottoms",
    Department: "Unisex Accessories",
    Price: " $89.99 ",
    Cost: " $61.64 ",
  },
  {
    ID: "SK08544",
    Label: "Retro-Inspired Sunglasses",
    Class: "Footwear",
    Department: "Women's Apparel",
    Price: " $44.99 ",
    Cost: " $41.12 ",
  },
  {
    ID: "SK08557",
    Label: "Formal Velvet Blazer",
    Class: "Bottoms",
    Department: "Sportswear",
    Price: " $194.99 ",
    Cost: " $189.14 ",
  },
  {
    ID: "SK08783",
    Label: "Striped Cotton Socks",
    Class: "Accessories",
    Department: "Footwear",
    Price: " $169.99 ",
    Cost: " $10.54 ",
  },
  {
    ID: "SK09245",
    Label: "Yoga Leggings",
    Class: "Bottoms",
    Department: "Unisex Accessories",
    Price: " $164.99 ",
    Cost: " $172.58 ",
  },
  {
    ID: "SK09312",
    Label: "Formal Dress Shoes",
    Class: "Bottoms",
    Department: "Sportswear",
    Price: " $9.99 ",
    Cost: " $1.96 ",
  },
  {
    ID: "SK09318",
    Label: "Aviator Sunglasses",
    Class: "Footwear",
    Department: "Sportswear",
    Price: " $44.99 ",
    Cost: " $12.37 ",
  },
  {
    ID: "SK09414",
    Label: "Perforated Leather Belt",
    Class: "Tops",
    Department: "Footwear",
    Price: " $44.99 ",
    Cost: " $4.50 ",
  },
  {
    ID: "SK09453",
    Label: "Smart Heated Gloves",
    Class: "Footwear",
    Department: "Unisex Accessories",
    Price: " $109.99 ",
    Cost: " $100.53 ",
  },
  {
    ID: "SK09469",
    Label: "Silk Embroidered Kimono",
    Class: "Jewelry",
    Department: "Sportswear",
    Price: " $109.99 ",
    Cost: " $78.64 ",
  },
  {
    ID: "SK09592",
    Label: "Performance Swim Trunks",
    Class: "Tops",
    Department: "Men's Apparel",
    Price: " $174.99 ",
    Cost: " $157.84 ",
  },
  {
    ID: "SK09659",
    Label: "Tactical Hiking Backpack",
    Class: "Jewelry",
    Department: "Women's Apparel",
    Price: " $69.99 ",
    Cost: " $58.16 ",
  },
  {
    ID: "SK09728",
    Label: "Thermal Running Gloves",
    Class: "Outerwear",
    Department: "Women's Apparel",
    Price: " $49.99 ",
    Cost: " $53.79 ",
  },
  {
    ID: "SK09816",
    Label: "Quilted Leather Clutch",
    Class: "Jewelry",
    Department: "Unisex Accessories",
    Price: " $134.99 ",
    Cost: " $95.84 ",
  },
  {
    ID: "SK10226",
    Label: "Rugged Utility Jacket",
    Class: "Accessories",
    Department: "Unisex Accessories",
    Price: " $44.99 ",
    Cost: " $2.43 ",
  },
  {
    ID: "SK10286",
    Label: "Tapered Suit Trousers",
    Class: "Bottoms",
    Department: "Men's Apparel",
    Price: " $64.99 ",
    Cost: " $53.10 ",
  },
  {
    ID: "SK10304",
    Label: "Faux Leather Leggings",
    Class: "Tops",
    Department: "Men's Apparel",
    Price: " $139.99 ",
    Cost: " $22.54 ",
  },
  {
    ID: "SK10514",
    Label: "Lace-Up Combat Boots",
    Class: "Tops",
    Department: "Sportswear",
    Price: " $109.99 ",
    Cost: " $64.89 ",
  },
  {
    ID: "SK10565",
    Label: "Athletic Crew Socks",
    Class: "Accessories",
    Department: "Unisex Accessories",
    Price: " $174.99 ",
    Cost: " $1.75 ",
  },
  {
    ID: "SK10717",
    Label: "Silk Neck Scarf",
    Class: "Outerwear",
    Department: "Footwear",
    Price: " $94.99 ",
    Cost: " $49.87 ",
  },
  {
    ID: "SK10760",
    Label: "Sherpa Lined Denim Jacket",
    Class: "Outerwear",
    Department: "Women's Apparel",
    Price: " $119.99 ",
    Cost: " $28.92 ",
  },
  {
    ID: "SK11103",
    Label: "Lace-Up Combat Boots",
    Class: "Outerwear",
    Department: "Men's Apparel",
    Price: " $24.99 ",
    Cost: " $24.84 ",
  },
  {
    ID: "SK11147",
    Label: "Sporty Zip-Up Hoodie",
    Class: "Footwear",
    Department: "Women's Apparel",
    Price: " $184.99 ",
    Cost: " $65.30 ",
  },
  {
    ID: "SK11260",
    Label: "Minimalist Gold Necklace",
    Class: "Footwear",
    Department: "Unisex Accessories",
    Price: " $104.99 ",
    Cost: " $52.08 ",
  },
  {
    ID: "SK11808",
    Label: "Classic Denim Jacket",
    Class: "Jewelry",
    Department: "Women's Apparel",
    Price: " $149.99 ",
    Cost: " $144.29 ",
  },
  {
    ID: "SK11860",
    Label: "Tassel Fringe Handbag",
    Class: "Accessories",
    Department: "Sportswear",
    Price: " $109.99 ",
    Cost: " $3.19 ",
  },
  {
    ID: "SK12148",
    Label: "Oversized Cat-Eye Sunglasses",
    Class: "Jewelry",
    Department: "Footwear",
    Price: " $159.99 ",
    Cost: " $109.11 ",
  },
  {
    ID: "SK12418",
    Label: "Minimalist Leather Watch",
    Class: "Bottoms",
    Department: "Unisex Accessories",
    Price: " $49.99 ",
    Cost: " $49.89 ",
  },
  {
    ID: "SK12460",
    Label: "Quilted Leather Clutch",
    Class: "Bottoms",
    Department: "Unisex Accessories",
    Price: " $4.99 ",
    Cost: " $0.68 ",
  },
  {
    ID: "SK12478",
    Label: "Floral Chiffon Wrap Dress",
    Class: "Footwear",
    Department: "Men's Apparel",
    Price: " $184.99 ",
    Cost: " $39.59 ",
  },
  {
    ID: "SK12670",
    Label: "Graphic Skateboard Tee",
    Class: "Bottoms",
    Department: "Women's Apparel",
    Price: " $194.99 ",
    Cost: " $53.43 ",
  },
  {
    ID: "SK12760",
    Label: "Minimalist Silver Ring",
    Class: "Tops",
    Department: "Unisex Accessories",
    Price: " $9.99 ",
    Cost: " $9.53 ",
  },
  {
    ID: "SK12773",
    Label: "Padded Winter Mittens",
    Class: "Tops",
    Department: "Unisex Accessories",
    Price: " $154.99 ",
    Cost: " $53.78 ",
  },
  {
    ID: "SK12919",
    Label: "Classic Denim Jacket",
    Class: "Jewelry",
    Department: "Footwear",
    Price: " $109.99 ",
    Cost: " $89.53 ",
  },
  {
    ID: "SK13050",
    Label: "Lace-Up Combat Boots",
    Class: "Tops",
    Department: "Women's Apparel",
    Price: " $134.99 ",
    Cost: " $75.59 ",
  },
  {
    ID: "SK13226",
    Label: "Cuffed Jogger Pants",
    Class: "Jewelry",
    Department: "Footwear",
    Price: " $69.99 ",
    Cost: " $64.95 ",
  },
  {
    ID: "SK13248",
    Label: "Oversized Hoodie",
    Class: "Outerwear",
    Department: "Men's Apparel",
    Price: " $124.99 ",
    Cost: " $23.25 ",
  },
  {
    ID: "SK13498",
    Label: "Unisex Oversized Sweatshirt",
    Class: "Jewelry",
    Department: "Men's Apparel",
    Price: " $139.99 ",
    Cost: " $77.13 ",
  },
  {
    ID: "SK13532",
    Label: "Puffer Insulated Vest",
    Class: "Tops",
    Department: "Sportswear",
    Price: " $14.99 ",
    Cost: " $10.72 ",
  },
  {
    ID: "SK13740",
    Label: "Faux Fur Winter Coat",
    Class: "Outerwear",
    Department: "Footwear",
    Price: " $14.99 ",
    Cost: " $4.56 ",
  },
  {
    ID: "SK13952",
    Label: "Tactical Hiking Backpack",
    Class: "Accessories",
    Department: "Footwear",
    Price: " $199.99 ",
    Cost: " $115.79 ",
  },
  {
    ID: "SK14045",
    Label: "Stretch Fit Slip-On Sneakers",
    Class: "Accessories",
    Department: "Unisex Accessories",
    Price: " $124.99 ",
    Cost: " $54.12 ",
  },
  {
    ID: "SK14051",
    Label: "Crew Neck Merino Wool Sweater",
    Class: "Tops",
    Department: "Women's Apparel",
    Price: " $19.99 ",
    Cost: " $3.62 ",
  },
  {
    ID: "SK14104",
    Label: "Handcrafted Wooden Watch",
    Class: "Bottoms",
    Department: "Footwear",
    Price: " $154.99 ",
    Cost: " $122.91 ",
  },
  {
    ID: "SK14223",
    Label: "Smart Heated Gloves",
    Class: "Tops",
    Department: "Women's Apparel",
    Price: " $34.99 ",
    Cost: " $4.13 ",
  },
  {
    ID: "SK14232",
    Label: "Luxury Silk Tie",
    Class: "Tops",
    Department: "Sportswear",
    Price: " $114.99 ",
    Cost: " $49.68 ",
  },
  {
    ID: "SK14409",
    Label: "Heavy-Duty Work Gloves",
    Class: "Tops",
    Department: "Women's Apparel",
    Price: " $164.99 ",
    Cost: " $63.03 ",
  },
  {
    ID: "SK14424",
    Label: "Waterproof Hiking Boots",
    Class: "Jewelry",
    Department: "Men's Apparel",
    Price: " $144.99 ",
    Cost: " $17.25 ",
  },
  {
    ID: "SK14528",
    Label: "Performance Swim Trunks",
    Class: "Footwear",
    Department: "Unisex Accessories",
    Price: " $114.99 ",
    Cost: " $41.51 ",
  },
  {
    ID: "SK14566",
    Label: "Feather Embellished Fedora",
    Class: "Outerwear",
    Department: "Sportswear",
    Price: " $184.99 ",
    Cost: " $193.87 ",
  },
  {
    ID: "SK14651",
    Label: "Floral Chiffon Wrap Dress",
    Class: "Tops",
    Department: "Footwear",
    Price: " $159.99 ",
    Cost: " $110.23 ",
  },
  {
    ID: "SK14807",
    Label: "Bamboo Fiber Boxer Briefs",
    Class: "Accessories",
    Department: "Men's Apparel",
    Price: " $89.99 ",
    Cost: " $7.74 ",
  },
  {
    ID: "SK14940",
    Label: "Woven Straw Sun Hat",
    Class: "Footwear",
    Department: "Women's Apparel",
    Price: " $99.99 ",
    Cost: " $9.70 ",
  },
  {
    ID: "SK14945",
    Label: "Silk Embroidered Kimono",
    Class: "Bottoms",
    Department: "Women's Apparel",
    Price: " $74.99 ",
    Cost: " $12.30 ",
  },
  {
    ID: "SK14974",
    Label: "Asymmetrical Hem Skirt",
    Class: "Bottoms",
    Department: "Footwear",
    Price: " $184.99 ",
    Cost: " $19.98 ",
  },
  {
    ID: "SK15217",
    Label: "Wool Fedora Hat",
    Class: "Footwear",
    Department: "Sportswear",
    Price: " $99.99 ",
    Cost: " $86.49 ",
  },
  {
    ID: "SK15290",
    Label: "Fleece Jogger Sweatpants",
    Class: "Footwear",
    Department: "Sportswear",
    Price: " $79.99 ",
    Cost: " $45.67 ",
  },
  {
    ID: "SK15291",
    Label: "Cuffed Jogger Pants",
    Class: "Outerwear",
    Department: "Sportswear",
    Price: " $114.99 ",
    Cost: " $52.90 ",
  },
  {
    ID: "SK15526",
    Label: "Relaxed Fit Cargo Pants",
    Class: "Bottoms",
    Department: "Women's Apparel",
    Price: " $199.99 ",
    Cost: " $80.80 ",
  },
  {
    ID: "SK15631",
    Label: "Velvet Slip Dress",
    Class: "Tops",
    Department: "Footwear",
    Price: " $164.99 ",
    Cost: " $106.75 ",
  },
  {
    ID: "SK15722",
    Label: "Cashmere Turtleneck Sweater",
    Class: "Accessories",
    Department: "Men's Apparel",
    Price: " $99.99 ",
    Cost: " $91.79 ",
  },
  {
    ID: "SK15739",
    Label: "High-Waisted Bikini Set",
    Class: "Outerwear",
    Department: "Sportswear",
    Price: " $64.99 ",
    Cost: " $69.34 ",
  },
  {
    ID: "SK15761",
    Label: "Minimalist Gold Necklace",
    Class: "Jewelry",
    Department: "Sportswear",
    Price: " $74.99 ",
    Cost: " $71.47 ",
  },
  {
    ID: "SK16210",
    Label: "Oversized Cat-Eye Sunglasses",
    Class: "Outerwear",
    Department: "Men's Apparel",
    Price: " $119.99 ",
    Cost: " $117.83 ",
  },
  {
    ID: "SK16364",
    Label: "Minimalist Silver Ring",
    Class: "Outerwear",
    Department: "Women's Apparel",
    Price: " $64.99 ",
    Cost: " $49.59 ",
  },
  {
    ID: "SK16370",
    Label: "Sherpa Lined Denim Jacket",
    Class: "Jewelry",
    Department: "Men's Apparel",
    Price: " $189.99 ",
    Cost: " $28.69 ",
  },
  {
    ID: "SK16474",
    Label: "Cropped Faux Leather Jacket",
    Class: "Outerwear",
    Department: "Women's Apparel",
    Price: " $39.99 ",
    Cost: " $21.03 ",
  },
  {
    ID: "SK16642",
    Label: "Tassel Fringe Handbag",
    Class: "Tops",
    Department: "Men's Apparel",
    Price: " $134.99 ",
    Cost: " $20.79 ",
  },
  {
    ID: "SK16722",
    Label: "Reflective Running Vest",
    Class: "Jewelry",
    Department: "Sportswear",
    Price: " $154.99 ",
    Cost: " $112.21 ",
  },
  {
    ID: "SK16745",
    Label: "Classic Denim Jacket",
    Class: "Footwear",
    Department: "Footwear",
    Price: " $24.99 ",
    Cost: " $22.29 ",
  },
  {
    ID: "SK16750",
    Label: "Faux Leather Leggings",
    Class: "Outerwear",
    Department: "Unisex Accessories",
    Price: " $64.99 ",
    Cost: " $43.02 ",
  },
  {
    ID: "SK16871",
    Label: "Woven Straw Sun Hat",
    Class: "Bottoms",
    Department: "Sportswear",
    Price: " $9.99 ",
    Cost: " $0.80 ",
  },
  {
    ID: "SK17623",
    Label: "Silk Embroidered Kimono",
    Class: "Footwear",
    Department: "Footwear",
    Price: " $134.99 ",
    Cost: " $48.06 ",
  },
  {
    ID: "SK17867",
    Label: "High-Slit Maxi Dress",
    Class: "Tops",
    Department: "Unisex Accessories",
    Price: " $9.99 ",
    Cost: " $7.85 ",
  },
  {
    ID: "SK18018",
    Label: "Fleece-Lined Parka",
    Class: "Tops",
    Department: "Footwear",
    Price: " $59.99 ",
    Cost: " $17.40 ",
  },
  {
    ID: "SK18148",
    Label: "Silk Neck Scarf",
    Class: "Bottoms",
    Department: "Men's Apparel",
    Price: " $114.99 ",
    Cost: " $120.62 ",
  },
  {
    ID: "SK18224",
    Label: "Unisex Oversized Sweatshirt",
    Class: "Accessories",
    Department: "Men's Apparel",
    Price: " $134.99 ",
    Cost: " $106.64 ",
  },
  {
    ID: "SK18623",
    Label: "Textured Knit Pullover",
    Class: "Jewelry",
    Department: "Men's Apparel",
    Price: " $34.99 ",
    Cost: " $33.38 ",
  },
  {
    ID: "SK18665",
    Label: "Luxury Silk Tie",
    Class: "Tops",
    Department: "Footwear",
    Price: " $54.99 ",
    Cost: " $20.95 ",
  },
  {
    ID: "SK18753",
    Label: "Rugged Utility Jacket",
    Class: "Outerwear",
    Department: "Women's Apparel",
    Price: " $29.99 ",
    Cost: " $20.69 ",
  },
  {
    ID: "SK18791",
    Label: "Retro-Inspired Sunglasses",
    Class: "Jewelry",
    Department: "Unisex Accessories",
    Price: " $79.99 ",
    Cost: " $82.55 ",
  },
  {
    ID: "SK19521",
    Label: "High-Slit Maxi Dress",
    Class: "Outerwear",
    Department: "Footwear",
    Price: " $14.99 ",
    Cost: " $6.49 ",
  },
  {
    ID: "SK19547",
    Label: "Boho Style Tassel Earrings",
    Class: "Outerwear",
    Department: "Men's Apparel",
    Price: " $104.99 ",
    Cost: " $11.02 ",
  },
  {
    ID: "SK19857",
    Label: "Metallic Hoop Earrings",
    Class: "Bottoms",
    Department: "Unisex Accessories",
    Price: " $84.99 ",
    Cost: " $35.61",
  },
];
