export const stores = [
  {
    ID: "ST035",
    Label: "San Francisco Bay Trends",
    City: "San Francisco",
    State: "CA",
  },
  {
    ID: "ST046",
    Label: "Phoenix Sunwear",
    City: "Phoenix",
    State: "AZ",
  },
  {
    ID: "ST064",
    Label: "Dallas Ranch Supply",
    City: "Dallas",
    State: "TX",
  },
  {
    ID: "ST066",
    Label: "Atlanta Outfitters",
    City: "Atlanta",
    State: "GA",
  },
  {
    ID: "ST073",
    Label: "Nashville Melody Music Store",
    City: "Nashville",
    State: "TN",
  },
  {
    ID: "ST074",
    Label: "New York Empire Eats",
    City: "New York",
    State: "NY",
  },
  {
    ID: "ST091",
    Label: "Denver Peaks Outdoor",
    City: "Denver",
    State: "CO",
  },
  {
    ID: "ST094",
    Label: "Philadelphia Liberty Market",
    City: "Philadelphia",
    State: "PA",
  },
  {
    ID: "ST097",
    Label: "Boston Harbor Books",
    City: "Boston",
    State: "MA",
  },
  {
    ID: "ST101",
    Label: "Austin Vibe Co.",
    City: "Austin",
    State: "TX",
  },
  {
    ID: "ST131",
    Label: "Los Angeles Luxe",
    City: "Los Angeles",
    State: "CA",
  },
  {
    ID: "ST150",
    Label: "Houston Harvest Market",
    City: "Houston",
    State: "TX",
  },
  {
    ID: "ST151",
    Label: "Portland Evergreen Goods",
    City: "Portland",
    State: "OR",
  },
  {
    ID: "ST156",
    Label: "Chicago Charm Boutique",
    City: "Chicago",
    State: "IL",
  },
  {
    ID: "ST163",
    Label: "Las Vegas Neon Treasures",
    City: "Las Vegas",
    State: "NV",
  },
  {
    ID: "ST175",
    Label: "Seattle Skyline Goods",
    City: "Seattle",
    State: "WA",
  },
  {
    ID: "ST176",
    Label: "Miami Breeze Apparel",
    City: "Miami",
    State: "FL",
  },
  {
    ID: "ST177",
    Label: "San Diego Wave Surf Shop",
    City: "San Diego",
    State: "CA",
  },
  {
    ID: "ST193",
    Label: "Charlotte Queen‚Äôs Closet",
    City: "Charlotte",
    State: "NC",
  },
  {
    ID: "ST208",
    Label: "Detroit Motor Gear",
    City: "Detroit",
    State: "MI",
  },
];
